### ISSUE TITLE
Evaluate Alectryon extensibility

### ISSUE THREAD

**Issue by insightmind** [insightmind/LeanInk#1]
# Task 

Take a look at the specifications and documentation of alectryon and figure out its extensibility.

Important points:
- How well does alectryon allow us to use the json format provided by it.
- In which degree do we need to extend its functionality to support Lean4
- Can call it directly from LeanInk, if so which way do we want to recommend?
- Find out important interface points between alectryon and a possible LeanInk interface

**Comment by insightmind** [comment]
Interesting note: Alectryon uses `pygments` for syntax highlighting.

**Comment by insightmind** [comment]
Files we have to adjust/add functionality to, so Alectryon supports Lean4:
- Create `lean4.py` for our custom Lean 4 driver. This is basically just an interface that communicates with LeanInk and sends LeanInk the file for analysis. Probably the easiest to just tell LeanInk the FilePath to the `.lean` file. We actually get `chunks` of the file here. We could get the whole file if we adjust the pipeline for lean4 in `cli.py`, we could also write the chunks to a fresh file instead.
- `cli.py` register the new frontend `lean4` and update add new pipelines if necessary. We must also decide how we make sure Alectryon chooses the right lean frontend when given a `.lean` file.
- `transform.py` needs some transforms ??? I actually did not dig deep into what transform do and why they are used but, we should probably have to do something here as well
- `literate.py` we need a converter for `.rst` to `.lean` (Lean 4) and the other way around. For the latter they implement a simple Lean parser.
- `docutils.py` some smaller adjustments to Pipeline APIs?
- `pygments...` for syntax highlighting

**Comment by Kha** [comment]
>     * We actually get `chunks` of the file here.

That's all the chunks at once, right? Then passing that list (e.g. as JSON) to LeanInk, fully processing it there, and then writing back the results seems like the most robust solution to me, if we don't want to e.g. parse `.rst` ourselves.

**Comment by Kha** [comment]
>     * We must also decide how we make sure Alectryon chooses the right lean frontend when given a `.lean` file.

I'd say let's just always assume Lean 4 for now. Lean 4 might be much closer to supplanting Lean 3 when we are done.

**Comment by insightmind** [comment]
> > ```
> > * We actually get `chunks` of the file here.
> > ```
> 
> 
> That's all the chunks at once, right? Then passing that list (e.g. as JSON) to LeanInk, fully processing it there, and then writing back the results seems like the most robust solution to me, if we don't want to e.g. parse `.rst` ourselves.

Yeah exactly. 

If we provide Alectryon a simple `.lean` code file, then the driver will get a single chunk with the whole source code of the file. However if we provide a preprocessed `.json` or some `.rst` file or so it may split up some parts of it into separate chunks, tho every chunk is expected to be a valid `.lean` program. 

In the case of an `.rst` file every chunk we get is a literate code block. So if we want them to be analyzed as a whole, because they may have common definitions and depend on each other, we could also merge all chunks into a single chunk, which we then write to a `.lean` file we can analyze directly instead of using `.json` as an intermediate format. This is actually the approach Alectryon uses in the `coqc` driver. 
The benefits of this are that we don't need to care about all the escaping stuff in json (ideally this is already solved by the json library in Python and Lean 4), as well as that LeanInk can actually use independent `.lean` files as inputs instead of a special format.

**Comment by insightmind** [comment]
> > ```
> > * We must also decide how we make sure Alectryon chooses the right lean frontend when given a `.lean` file.
> > ```
> 
> 
> I'd say let's just always assume Lean 4 for now. Lean 4 might be much closer to supplanting Lean 3 when we are done.

Does Lean 4 support the `.lean4` extension similar to Lean 3 `.lean3`?

**Comment by Kha** [comment]
> This is actually the approach Alectryon uses in the `coqc` driver.

I see, then I suppose it should work for us as well. I had imagined that it would make transforming positions back to the source document harder.

**Comment by Kha** [comment]
> Does Lean 4 support the `.lean4` extension similar to Lean 3 `.lean3`?

Unfortunately no, they both use `.lean` only.
