### ISSUE TITLE
Implement first working prototype

### ISSUE THREAD

**Issue by insightmind** [insightmind/LeanInk#3]
Features necessary to make LeanInk prototype work:

- [x] Load LeanFile
- [x] Encode result in AlectryonFragments format (json format).
- [ ] Split LeanFile in `Text` and `Sentence`, according to the AlectryonFormat. Each `Text` is, as the name suggest, only a plain  text fragment that gets rendered in the output file. A `Sentence` additionally includes `messages` and `goals`. (we should probably document the whole interface format separately).
- [ ] Record errors within the LeanFile? Crash on error or continue as good as we can?

**Comment by insightmind** [comment]
Update:
The above list was a bit naive as there are more steps involved in making the prototype work.
The current implementation status is as follows:

1) Loads a lean file
2) Loads the searchPaths for the Init module (lake support still missing, because requires improved CLI interface)
3) Extracts the InfoTree from the Elab.frontend
4) Extracts some unparsed metadata from the InfoTrees (most work still needs to be done here). The extraction result is a list if this metadata sorted by the startPos of each metadata.
5) We use the sorted metadata and generate an IntervalTree from it.
6) We iterate naively (can be optimized) over the given text range of the input file. At each position we query through the IntervalTree to find all metadata that contains information about the current position. During iteration we create a list of compound annotations sorted from front to back of the text.
7) TODO: Use the contents of the input file and transform the annotations to AlectryonFragments
8) Writes the AlectryonFragments in json format to a temporary file `input_path.leanInk`

**Comment by Kha** [comment]
Naively I would hope that steps 4-6 can be combined into a single traversal over the info tree, which is already properly structured & sorted (...I think?). Might be simpler to discuss in person though.

**Comment by insightmind** [comment]
Yeah I totally agree, however I was not able to get it to work like this just yet, so I tried "a preliminary and less ideal" option.

An InfoTree `node` does not assure that its children are sorted (or at least that's how it currently works, see the `infoTree.lean` test in the lean repository for such a case), but that's basically the only issue. I already sort it during my extraction traversal. If the InfoTree assures that the tailPos of a parent node is the least upper bound of any of its child node then most of the structure of an interval tree is already fulfilled, in which case we could just merge the two steps into a single step. 

The issue with a single traversal is the most difficult one tho. The lean server for example currently only tries to find the smallest possible info at a given point/position. In our case we have to find them for every possible position in the given text range (we may also have to think about the granularity of the search, as the server implementation is very fine-grained) 
More exactly we have to partition the input text range into disjoint ranges of overlapping infos, which we can then use to transform into Alectryon's fragment format.

My main goal at the moment was to implement a workable structure (probably not ideal structure), that works for a prototype. If that's done I planned to try to improve the steps and merge them if possible + make extensions to the functionality.

But I'm sure we can find a way to combine these steps, which is also a good discussion topic in the next in-person meeting.
